<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CapaLogica</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Capa Datos\CapaDatos.csproj" />
    <ProjectReference Include="..\Capa Modelo\CapaModelo.csproj" />
  </ItemGroup>

</Project>
